version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      # Mount source code for hot reloading
      - ./src:/app/src
      # Exclude node_modules from being overwritten
      - /app/node_modules
    environment:
      - NODE_ENV=development
    # Keep the container running
    stdin_open: true
    tty: true